trigger:
- master

pool:
  vmImage: $(vmImageName)

variables:
  vmImageName: 'ubuntu-20.04'
  azureServiceConnection: '6e9da8b2-290f-4420-a94a-3c33a4a15dcc'
  resourceGroup: 'viz-wizard'
  dockerRegistryServiceConnection: 'c64c5d60-6159-4e64-ab50-c77326148c35'
  location: 'eastus'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: 'latest'

stages:
- stage: Build 
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
   
    - task: Docker@2
      displayName: Build and push image to container registry
      inputs:
        command: buildAndPush
        repository: app
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)